development:
  adapter: postgresql
  encoding: unicode
  database: nsa_snowden_development
  pool: 5
  host: localhost
  username: davidaaron
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: nsa_snowden_test
  pool: 5
  host: localhost
  username: davidaaron
  password: